[package]
name = "follon-accounting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
follon-domain = { path = "../domain" }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
