[package]
name = "follon-ibkr-paper-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
follon-paper = { path = "../../../core/paper" }
follon-domain = { path = "../../../core/domain" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
