[package]
name = "follon-instrument"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
follon-domain = { path = "../domain" }
follon-fx = { path = "../fx" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
