"""Deterministic strategy-bundle identities and dependency locks for reproducible workers.

A bundle is two source namespaces -- the declared strategy tree and the Follon
SDK the worker imports -- plus the Python runtime identity. The bundle hash is
SHA-256 over one length-framed byte stream of exactly those inputs. That byte
stream is also the portable archive a strategy capsule carries, so a capsule's
archive digest and the hash a worker announces are the same number by
construction (see ``core/control-plane/src/capsule.rs``).

The dependency lock records every file of both namespaces with its size and
digest, the runtime identity, and the strategy entry point. It is produced from
the same enumeration as the hash, so the two cannot disagree. Third-party
dependencies must be vendored below the strategy root; a capsule replay runs
the interpreter without ``site`` so an un-vendored import fails there rather
than silently resolving against whatever is installed.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
from pathlib import Path
import re
import sys

from .models import _canonical_id

BUNDLE_FORMAT = "follon-strategy-bundle-v2"
LOCK_SCHEMA_VERSION = 1
_PYTHON_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _sha256(name: str, value: str) -> str:
    if len(value) != 64 or any(character not in "0123456789abcdef" for character in value):
        raise ValueError(f"{name} must be a lowercase SHA-256 digest")
    return value


def strategy_bundle_runtime() -> str:
    """Returns the runtime identity bound into every bundle hash."""

    return (
        f"{sys.implementation.name}|"
        f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}|"
        f"{sys.platform}"
    )


def strategy_bundle_hash(root: str | Path) -> str:
    """Hashes strategy source, the SDK runtime, and Python runtime identity.

    Symlinks are rejected and generated bytecode is ignored. Third-party
    strategy dependencies must be vendored below ``root`` so they become part
    of this identity. The SDK is included automatically because changing its
    validation or serialization behavior can change a result even when
    strategy source is unchanged.
    """

    return _bundle_digest(_bundle_namespaces(root), strategy_bundle_runtime())


def strategy_bundle_lock(root: str | Path, strategy_file: str | Path, class_name: str) -> bytes:
    """Returns the canonical dependency lock for the bundle rooted at ``root``.

    ``strategy_file`` must be one of the bundle's own source files and
    ``class_name`` the strategy class it defines. The output is sorted-key,
    compact, ASCII JSON so its SHA-256 is a stable identity.
    """

    namespaces = _bundle_namespaces(root)
    strategy_root = _bundle_root(root)
    try:
        entry = Path(strategy_file).resolve(strict=True).relative_to(strategy_root).as_posix()
    except (FileNotFoundError, ValueError) as error:
        raise ValueError("strategy file must be a source file inside the bundle root") from error
    if entry not in {path for path, _ in namespaces[0][1]}:
        raise ValueError("strategy file must be a source file inside the bundle root")
    if not _PYTHON_IDENTIFIER.fullmatch(class_name):
        raise ValueError("strategy class name must be an ASCII Python identifier")
    runtime = strategy_bundle_runtime()
    document = {
        "bundle_format": BUNDLE_FORMAT,
        "entry_point": {"class_name": class_name, "strategy_file": entry},
        "lock_schema_version": LOCK_SCHEMA_VERSION,
        "namespaces": [
            {
                "files": [
                    {"bytes": len(contents), "path": path, "sha256": sha256(contents).hexdigest()}
                    for path, contents in files
                ],
                "name": name,
            }
            for name, files in namespaces
        ],
        "runtime": runtime,
        "strategy_bundle_hash": _bundle_digest(namespaces, runtime),
    }
    return json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode(
        "ascii"
    )


_Namespaces = tuple[tuple[str, list[tuple[str, bytes]]], ...]


def _bundle_root(root: str | Path) -> Path:
    resolved_root = Path(root).resolve(strict=True)
    if not resolved_root.is_dir() or resolved_root.is_symlink():
        raise ValueError("strategy bundle root must be a non-symlink directory")
    return resolved_root


def _bundle_namespaces(root: str | Path) -> _Namespaces:
    return (
        ("strategy", _source_files(_bundle_root(root))),
        ("sdk", _source_files(Path(__file__).resolve().parent)),
    )


def _source_files(root: Path) -> list[tuple[str, bytes]]:
    files = sorted(
        (path for path in root.rglob("*.py") if path.is_file()),
        key=lambda path: path.relative_to(root).as_posix(),
    )
    if not files:
        raise ValueError("strategy bundle contains no Python source files")
    sources = []
    for path in files:
        if path.is_symlink():
            raise ValueError("strategy bundle cannot contain symlinked source")
        sources.append((path.relative_to(root).as_posix(), path.read_bytes()))
    return sources


def _bundle_digest(namespaces: _Namespaces, runtime: str) -> str:
    """Hashes the framed bundle stream; its preimage is the capsule archive."""

    digest = sha256()
    digest.update(f"{BUNDLE_FORMAT}\0".encode("ascii"))
    for name, files in namespaces:
        encoded_name = name.encode("utf-8")
        digest.update(len(encoded_name).to_bytes(4, "big"))
        digest.update(encoded_name)
        for path, contents in files:
            relative = path.encode("utf-8")
            digest.update(len(relative).to_bytes(4, "big"))
            digest.update(relative)
            digest.update(len(contents).to_bytes(8, "big"))
            digest.update(contents)
    encoded_runtime = runtime.encode("utf-8")
    digest.update(len(encoded_runtime).to_bytes(4, "big"))
    digest.update(encoded_runtime)
    return digest.hexdigest()


@dataclass(frozen=True, slots=True)
class StrategyBundle:
    """Immutable strategy identity announced by an isolated worker."""

    strategy_id: str
    strategy_version: str
    bundle_hash: str

    def __post_init__(self) -> None:
        _canonical_id("strategy_id", self.strategy_id)
        if not self.strategy_version:
            raise ValueError("strategy_version is required")
        _sha256("bundle_hash", self.bundle_hash)
