"""Deterministic strategy-bundle identities for reproducible workers."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
import sys

from .models import _canonical_id


def _sha256(name: str, value: str) -> str:
    if len(value) != 64 or any(character not in "0123456789abcdef" for character in value):
        raise ValueError(f"{name} must be a lowercase SHA-256 digest")
    return value


def strategy_bundle_hash(root: str | Path) -> str:
    """Hashes strategy source, the SDK runtime, and Python runtime identity.

    Symlinks and generated bytecode are rejected. Third-party strategy
    dependencies must be vendored below ``root`` so they become part of this
    identity. The SDK is included automatically because changing its validation
    or serialization behavior can change a result even when strategy source is
    unchanged.
    """

    resolved_root = Path(root).resolve(strict=True)
    if not resolved_root.is_dir() or resolved_root.is_symlink():
        raise ValueError("strategy bundle root must be a non-symlink directory")
    digest = sha256()
    digest.update(b"follon-strategy-bundle-v2\0")
    _hash_source_tree(digest, b"strategy", resolved_root)
    _hash_source_tree(digest, b"sdk", Path(__file__).resolve().parent)
    runtime = (
        f"{sys.implementation.name}|"
        f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}|"
        f"{sys.platform}"
    ).encode("utf-8")
    digest.update(len(runtime).to_bytes(4, "big"))
    digest.update(runtime)
    return digest.hexdigest()


def _hash_source_tree(digest, namespace: bytes, root: Path) -> None:
    files = sorted(
        (path for path in root.rglob("*.py") if path.is_file()),
        key=lambda path: path.relative_to(root).as_posix(),
    )
    if not files:
        raise ValueError("strategy bundle contains no Python source files")
    digest.update(len(namespace).to_bytes(4, "big"))
    digest.update(namespace)
    for path in files:
        if path.is_symlink():
            raise ValueError("strategy bundle cannot contain symlinked source")
        relative = path.relative_to(root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        contents = path.read_bytes()
        digest.update(len(contents).to_bytes(8, "big"))
        digest.update(contents)


@dataclass(frozen=True, slots=True)
class StrategyBundle:
    """Immutable strategy identity announced by an isolated worker."""

    strategy_id: str
    strategy_version: str
    bundle_hash: str

    def __post_init__(self) -> None:
        _canonical_id("strategy_id", self.strategy_id)
        if not self.strategy_version:
            raise ValueError("strategy_version is required")
        _sha256("bundle_hash", self.bundle_hash)
