"""Deterministic strategy-bundle identities for reproducible workers."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path

from .models import _canonical_id


def _sha256(name: str, value: str) -> str:
    if len(value) != 64 or any(character not in "0123456789abcdef" for character in value):
        raise ValueError(f"{name} must be a lowercase SHA-256 digest")
    return value


def strategy_bundle_hash(root: str | Path) -> str:
    """Hashes every Python source file below ``root`` in stable path order.

    Symlinks, generated bytecode, and files outside the declared root are
    rejected. A bundle caller should ship exactly this directory with the
    worker; imported code outside it is intentionally not part of the trusted
    strategy identity.
    """

    resolved_root = Path(root).resolve(strict=True)
    if not resolved_root.is_dir() or resolved_root.is_symlink():
        raise ValueError("strategy bundle root must be a non-symlink directory")
    files = sorted(
        (path for path in resolved_root.rglob("*.py") if path.is_file()),
        key=lambda path: path.relative_to(resolved_root).as_posix(),
    )
    if not files:
        raise ValueError("strategy bundle contains no Python source files")

    digest = sha256()
    for path in files:
        if path.is_symlink():
            raise ValueError("strategy bundle cannot contain symlinked source")
        relative = path.relative_to(resolved_root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        contents = path.read_bytes()
        digest.update(len(contents).to_bytes(8, "big"))
        digest.update(contents)
    return digest.hexdigest()


@dataclass(frozen=True, slots=True)
class StrategyBundle:
    """Immutable strategy identity announced by an isolated worker."""

    strategy_id: str
    strategy_version: str
    bundle_hash: str

    def __post_init__(self) -> None:
        _canonical_id("strategy_id", self.strategy_id)
        if not self.strategy_version:
            raise ValueError("strategy_version is required")
        _sha256("bundle_hash", self.bundle_hash)
